Repository My-Solar-Garden/front_end_rails, pull requests merged in 2020-11, with the labels that each got.

#79 Welcome Page
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.scss
  app/controllers/learn_more_controller.rb
  app/controllers/welcome_controller.rb
  app/views/layouts/application.html.erb
  app/views/learn_more/show.html.erb
  app/views/welcome/index.html.erb
  spec/features/learn_more/show_spec.rb
  spec/features/welcome/index_spec.rb
Labels: front_end, view

#81 Fixing skipped tests
  app/controllers/sessions_controller.rb
  spec/features/navbar/navbar_spec.rb
  spec/features/sessions/logout_spec.rb
  spec/features/welcome/index_spec.rb
  spec/fixtures/vcr_cassettes/google_oauth.yml
Labels: front_end, view

#92 User Pages w/ API Calls
  app/controllers/users_controller.rb
  app/facades/user_facade.rb
  app/services/user_service.rb
  app/views/layouts/application.html.erb
  app/views/users/edit.html.erb
  app/views/users/show.html.erb
  config/routes.rb
  spec/facades/user_facade_spec.rb
  spec/features/navbar/navbar_spec.rb
  spec/features/users/destroy_spec.rb
  spec/features/users/edit_spec.rb
  spec/features/users/show_spec.rb
  spec/fixtures/user_update.json
  spec/services/user_service_spec.rb
Labels: API, back_end, front_end, mvp

#91 Sensor button
  app/controllers/sessions_controller.rb
  app/poros/user.rb
  app/views/gardens/show.html.erb
  app/views/welcome/index.html.erb
  spec/features/gardens/show_spec.rb
  spec/features/welcome/index_spec.rb
Labels: front_end, view

#93 Create new garden
  app/controllers/application_controller.rb
  app/controllers/dashboard_controller.rb
  app/controllers/gardens_controller.rb
  app/facades/garden_facade.rb
  app/services/garden_service.rb
  app/views/dashboard/show.html.erb
  app/views/gardens/new.html.erb
  app/views/layouts/application.html.erb
  app/views/shared/_users_gardens_index.html.erb
  config/routes.rb
  spec/facades/garden_facade_spec.rb
  spec/features/dashboard/show_spec.rb
  spec/features/gardens/edit_spec.rb
  spec/features/gardens/new_spec.rb
  spec/features/learn_more/show_spec.rb
  spec/features/navbar/navbar_spec.rb
  spec/fixtures/new_garden.json
  spec/helpers.rb
  spec/rails_helper.rb
  spec/services/garden_service_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#95 Sessions Refactor
  app/controllers/sessions_controller.rb
  app/facades/session_facade.rb
  app/poros/user.rb
  app/services/garden_service.rb
  app/services/session_service.rb
  app/services/user_service.rb
  spec/facades/session_facade_spec.rb
  spec/features/gardens/show_spec.rb
  spec/features/navbar/navbar_spec.rb
  spec/features/users/edit_spec.rb
  spec/fixtures/garden_with_sensors.json
  spec/helpers.rb
  spec/services/garden_service_spec.rb
  spec/services/session_service_spec.rb
Labels: front_end, view

#109 Add delete garden functionality + add FontAwesome gem
  Gemfile
  Gemfile.lock
  app/assets/images/edit-garden.png
  app/assets/images/trash-garden.png
  app/assets/stylesheets/application.scss
  app/controllers/application_controller.rb
  app/controllers/gardens_controller.rb
  app/facades/garden_facade.rb
  app/services/garden_service.rb
  app/views/shared/_users_gardens_index.html.erb
  config/routes.rb
  spec/facades/garden_facade_spec.rb
  spec/features/dashboard/show_spec.rb
  spec/features/gardens/destroy_spec.rb
  spec/fixtures/delete_garden.json
  spec/services/garden_service_spec.rb
Labels: enhancement

#123 404 testing
  config/routes.rb
  spec/facades/garden_facade_spec.rb
  spec/features/gardens/edit_spec.rb
  spec/features/gardens/index_spec.rb
  spec/features/gardens/new_spec.rb
  spec/features/learn_more/show_spec.rb
  spec/features/plants/new_spec.rb
  spec/features/plants/show_spec.rb
  spec/features/sensors/delete_spec.rb
  spec/features/sensors/new_spec.rb
  spec/features/sensors/show_spec.rb
  spec/features/users/edit_spec.rb
  spec/features/users/show_spec.rb
  spec/services/garden_service_spec.rb
Labels: front_end, view

#127 Edit garden
  app/controllers/gardens_controller.rb
  app/facades/garden_facade.rb
  app/services/garden_service.rb
  app/views/gardens/edit.html.erb
  spec/facades/garden_facade_spec.rb
  spec/features/gardens/edit_spec.rb
  spec/fixtures/updated_garden.json
  spec/fixtures/vcr_cassettes/GardenService/returns_create_new_garden_response.yml
  spec/services/garden_service_spec.rb
Labels: enhancement

#129 General refactor: NavBar, Welcome Index, Garden Index
  app/views/layouts/application.html.erb
  app/views/shared/_users_gardens_index.html.erb
  app/views/welcome/index.html.erb
  spec/features/dashboard/show_spec.rb
  spec/features/learn_more/show_spec.rb
  spec/features/navbar/navbar_spec.rb
  spec/features/welcome/index_spec.rb
  spec/fixtures/vcr_cassettes/On_the_garden_show_page/as_a_logged_in_user/I_can_delete_a_sensor.yml
Labels: front_end, view
